buildscript {
    repositories {
        mavenCentral()
        maven {
           url = 'https://repo.grails.org/grails/restricted'
        }
    }
    dependencies { // Not Published to Gradle Plugin Portal
        classpath "cloud.wondrify:asset-pipeline-gradle"
        classpath platform("org.apache.grails:grails-bom:$grailsVersion")
        classpath "org.apache.grails:grails-gradle-plugins"
    }
}

plugins {
    id "war"
    id "idea"
    id "eclipse"
    id "maven-publish"
}

// Not Published to Gradle Plugin Portal
apply plugin: "org.apache.grails.gradle.grails-gsp"
apply plugin: "cloud.wondrify.asset-pipeline"
apply plugin: "org.apache.grails.gradle.grails-plugin"

group "org.grails.plugins"

repositories {
    mavenCentral()
    maven {
       url = 'https://repo.grails.org/grails/restricted'
    }
}

dependencies {
    profile "org.apache.grails.profiles:web-plugin"
    developmentOnly "org.springframework.boot:spring-boot-devtools" // Spring Boot DevTools may cause performance slowdowns or compatibility issues on larger applications
    testAndDevelopmentOnly "org.webjars.npm:bootstrap"
    testAndDevelopmentOnly "org.webjars.npm:bootstrap-icons"
    testAndDevelopmentOnly "org.webjars.npm:jquery"

    // export plugin specific dependencies
    api 'com.opencsv:opencsv:5.12.0'

    api 'com.github.librepdf:openpdf:1.4.2'
    api 'com.github.librepdf:openrtf:1.2.1'
    runtimeOnly 'xerces:xercesImpl:2.12.2'

    api 'org.odftoolkit:simple-odf:0.9.0'
    api 'org.apache.poi:poi:5.5.1'
    api 'org.apache.poi:poi-ooxml:5.5.1'

    api 'commons-beanutils:commons-beanutils:1.11.0'
    api 'commons-codec:commons-codec:1.21.0'


    // default plugin dependencies
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")
    implementation "org.apache.grails:grails-core"
    implementation "org.apache.grails:grails-events"
    implementation "org.apache.grails:grails-gsp"
    implementation "org.apache.grails:grails-interceptors"
    implementation "org.apache.grails:grails-layout"
    implementation "org.apache.grails:grails-logging"
    implementation "org.apache.grails:grails-scaffolding"
    implementation "org.apache.grails:grails-services"
    implementation "org.apache.grails:grails-url-mappings"
    implementation "org.apache.grails:grails-web-boot"

    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    console "org.apache.grails:grails-console"
    runtimeOnly "cloud.wondrify:asset-pipeline-grails"
    runtimeOnly "org.fusesource.jansi:jansi"
    testImplementation "org.apache.grails:grails-testing-support-datamapping"
    testImplementation "org.apache.grails:grails-testing-support-web"
    testImplementation "org.spockframework:spock-core"
}

compileJava.options.release = 17

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

assets {
    packagePlugin = true
    excludes = [
            'webjars/jquery/**',
            'webjars/bootstrap/**',
            'webjars/bootstrap-icons/**',
    ]
    includes = [
            'webjars/jquery/*/dist/jquery.js',
            'webjars/bootstrap/*/dist/js/bootstrap.bundle.js',
            'webjars/bootstrap/*/dist/css/bootstrap.css',
            'webjars/bootstrap-icons/*/font/bootstrap-icons.css',
            'webjars/bootstrap-icons/*/font/fonts/*',
    ]
}

jar {
    exclude 'gsp**'
    exclude '**/*.svg'
    exclude '**/*.ico'
    exclude 'layouts/'
    exclude 'test/'

    List excludes = ['UrlMappings', 'TestController']
    excludes.each {
        exclude "**/${it}*.class"
    }
    archiveClassifier=''
}

publishing {
    publications {
        maven(MavenPublication) {
            pom {
                name = "Grails Export Plugin"
                description = "This plugin offers export functionality supporting different formats e.g. CSV, Excel, Open Document Spreadsheet, PDF and XML and can be extended to add additional formats."

                licenses {
                    license {
                        name = "The Apache License, Version 2.0"
                        url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }
                developers {
                    developer { id = "graemerocher"; name = 'Graeme Rocher' }
                    developer { id = "puneetbehl"; name = 'Puneet Behl' }
                    developer { id = "nwwells"; name = 'Nathan Wells' }
                    developer { id = "tulu"; name = 'Ruben' }
                    developer { id = "arturoojeda"; name = 'Arturo Ojeda López' }
                    developer { id = "fabiooshiro"; name = 'Fabio Issamu Oshiro' }
                    developer { id = "ddelponte"; name = 'Dean Del Ponte' }
                    developer { id = "cristallo"; name = 'Cristiano Limiti' }
                    developer { id = "mirweb"; name = 'Mirko Weber' }
                    developer { id = "joasgarcia"; name = 'Joás Garcia' }
                    developer { id = "frangarcia"; name = 'Fran García' }
                    developer { id = "dustindclark"; name = 'Dustin Clark' }
                    developer { id = "miq"; name = 'Mihael Koep'; email = 'mihael.koep@softwareschneiderei.de' }
                }
            }

            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            from components.java
            repositories {
                maven {
                    credentials {
                        username "$mavenUser"
                        password "$mavenPassword"
                    }
                    url "$mavenUrl"
                }
            }
        }
    }
}

// https://github.com/apache/grails-core/issues/15321
tasks.withType(GroovyCompile).configureEach {
    groovyOptions.optimizationOptions.indy = false
}
